_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: nl
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  colorbox: 0
  components: 0
  config: 0
  config_ignore: 0
  config_translation: 0
  contextual: 0
  crop: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  facets: 0
  fb_likebox: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  focal_point: 0
  gtm: 0
  image: 0
  image_effects: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_builder_component_attributes: 0
  layout_builder_styles: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_clickthrough: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  node_keep: 0
  options: 0
  overview_field: 0
  page_cache: 0
  paragraphs_asymmetric_translation_widgets: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  recaptcha: 0
  redirect: 0
  responsive_image: 0
  rh_taxonomy: 0
  sa: 0
  sa_paragraphs: 0
  sdc: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  slick: 0
  slick_ui: 0
  stage_file_proxy: 0
  storybook: 0
  styleguide: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  webform: 0
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stark: 0
  claro: 0
  stable: 0
  classy: 0
  splash: 0
profile: minimal
