_core:
  default_config_hash: LqXuXXQCTd1NWw7dGLef0PCi3_aEEWQuogAblo4hHaE
langcode: nl
hotlink: false
origin: ''
origin_dir: ''
proxy_headers: ''
use_imagecache_root: true
verify: true
excluded_extensions: ''
