_core:
  default_config_hash: t7clj3mzmOGrXX0HuCH5usf0vEqRtnMTBFVBIEmZ5pc
langcode: nl
first_day: 0
country:
  default: NL
timezone:
  default: Europe/Amsterdam
  user:
    configurable: true
    default: 0
    warn: false
